# Generated by Django 3.2.5 on 2023-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0003_student_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room_no',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
