# Generated by Django 3.2.5 on 2023-08-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0007_auto_20230822_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Donor',
        ),
    ]
