# Generated by Django 3.2.5 on 2023-08-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0008_rename_student_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
