# Generated by Django 3.2.5 on 2023-08-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0009_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='quantity',
        ),
    ]
